### ISSUE TITLE
IPFS daemon becomes unresponsive

### ISSUE THREAD

**Issue by rabbit** [AkashaProject/Alpha#8]
## Summary

The Akasha IPFS daemon hangs without apparent cause. When this happens portions of the app become unresponsive or unavailable. The issue is opaque to the user, no notifications or warnings are given, and restarting the app shows the IPFS icon in red.

## Reproduce Steps

No known steps to reproduce however this happened after allowing Akasha to run in the background unattended for some time (<2 hours) and was in affect once user attempted to add a link to profile by seeing a disabled submission button.

## System Information

Known to impact at least two OSX systems. Tested personally with ...

- 2015 Macbook Pro
- OSX 10.11
- No prior instances of geth or ipfs were running

**Comment by rabbit** [comment]
`ipfs.error.log`
```
{"level":"error","message":"Error: no ipfs repo found in /Users/rabbit/.ipfs.\nplease run: ipfs init\n","timestamp":"2016-12-23T06:43:23.374Z"}
{"level":"error","message":"\u001b[0;37m00:53:34.262 \u001b[31mERROR \u001b[0;34m      mdns: \u001b[0mmdns lookup error: failed to bind to any unicast udp port \u001b[0;37mmdns.go:131\u001b[0m\n","timestamp":"2016-12-23T06:53:34.262Z"}
{"level":"error","message":"\u001b[0;37m00:56:50.026 \u001b[31mERROR \u001b[0;34m       dht: \u001b[0mno addresses on peer being sent!\n\t\t\t\t\t[local:<peer.ID PKSwzf>]\n\t\t\t\t\t[sending:<peer.ID bJgvyh>]\n\t\t\t\t\t[remote:<peer.ID WcyHKo>] \u001b[0;37mhandlers.go:75\u001b[0m\n","timestamp":"2016-12-23T06:56:50.027Z"}
{"level":"error","message":"\u001b[0;37m01:23:34.262 \u001b[31mERROR \u001b[0;34m      mdns: \u001b[0mmdns lookup error: failed to bind to any unicast udp port \u001b[0;37mmdns.go:131\u001b[0m\n","timestamp":"2016-12-23T07:23:34.262Z"}
{"level":"error","message":"\u001b[0;37m11:10:21.152 \u001b[31mERROR \u001b[0;34m       dht: \u001b[0mno addresses on peer being sent!\n\t\t\t\t\t[local:<peer.ID PKSwzf>]\n\t\t\t\t\t[sending:<peer.ID TVsocF>]\n\t\t\t\t\t[remote:<peer.ID WcyHKo>] \u001b[0;37mhandlers.go:75\u001b[0m\n","timestamp":"2016-12-23T17:10:21.153Z"}
{"level":"error","message":"\u001b[0;37m12:10:44.379 \u001b[31mERROR \u001b[0;34mcore/serve: \u001b[0mPath Resolve error: Failed to get block for QmcvZ8YUQsQQeSk9j6M46MWwWY2h5rz15hwLYGRCQtq3uK: context canceled \u001b[0;37mgateway_handler.go:509\u001b[0m\n\u001b[0;37m12:10:44.379 \u001b[31mERROR \u001b[0;34mcore/serve: \u001b[0mPath Resolve error: Failed to get block for QmafJsXHkJ2sZ4f8YoUyQuAphP1HpoggDRX1Aob1gJ6eyk: context canceled \u001b[0;37mgateway_handler.go:509\u001b[0m\n","timestamp":"2016-12-23T18:10:44.476Z"}
{"level":"error","message":"\u001b[0;37m12:28:25.362 \u001b[31mERROR \u001b[0;34m      mdns: \u001b[0mmdns lookup error: failed to bind to any unicast udp port \u001b[0;37mmdns.go:131\u001b[0m\n","timestamp":"2016-12-23T18:28:25.364Z"}
{"level":"error","message":"\u001b[0;37m12:29:09.080 \u001b[31mERROR \u001b[0;34m       dht: \u001b[0mno addresses on peer being sent!\n\t\t\t\t\t[local:<peer.ID PKSwzf>]\n\t\t\t\t\t[sending:<peer.ID NRV7ky>]\n\t\t\t\t\t[remote:<peer.ID WcyHKo>] \u001b[0;37mhandlers.go:75\u001b[0m\n","timestamp":"2016-12-23T18:29:09.081Z"}
{"level":"error","message":"\u001b[0;37m12:40:29.770 \u001b[31mERROR \u001b[0;34m       dht: \u001b[0mno addresses on peer being sent!\n\t\t\t\t\t[local:<peer.ID PKSwzf>]\n\t\t\t\t\t[sending:<peer.ID ZziavL>]\n\t\t\t\t\t[remote:<peer.ID WcyHKo>] \u001b[0;37mhandlers.go:75\u001b[0m\n","timestamp":"2016-12-23T18:40:29.771Z"}
{"level":"error","message":"\u001b[0;37m13:02:28.117 \u001b[31mERROR \u001b[0;34m      mdns: \u001b[0mmdns lookup error: failed to bind to any multicast udp port \u001b[0;37mmdns.go:131\u001b[0m\n","timestamp":"2016-12-23T19:02:28.118Z"}
{"level":"error","message":"\u001b[0;37m13:35:39.109 \u001b[31mERROR \u001b[0;34m       dht: \u001b[0mno addresses on peer being sent!\n\t\t\t\t\t[local:<peer.ID PKSwzf>]\n\t\t\t\t\t[sending:<peer.ID a7U9CN>]\n\t\t\t\t\t[remote:<peer.ID WcyHKo>] \u001b[0;37mhandlers.go:75\u001b[0m\n","timestamp":"2016-12-23T19:35:39.110Z"}
{"level":"error","message":"Error: ipfs daemon is running. please stop it to run this command\nUse 'ipfs daemon --help' for information about this command\n","timestamp":"2016-12-23T20:50:44.444Z"}
{"level":"error","message":"Error: ipfs daemon is running. please stop it to run this command\nUse 'ipfs daemon --help' for information about this command\n","timestamp":"2016-12-23T20:51:06.674Z"}
```

`ipfs.info.log`
```
{"level":"info","message":"Initializing daemon...\n","timestamp":"2016-12-23T06:43:23.372Z"}
{"level":"error","message":"Error: no ipfs repo found in /Users/rabbit/.ipfs.\nplease run: ipfs init\n","timestamp":"2016-12-23T06:43:23.374Z"}
{"level":"info","message":"ipfs exited with code: 1, signal: null ","timestamp":"2016-12-23T06:43:23.377Z"}
{"level":"info","message":"Initializing daemon...\n","timestamp":"2016-12-23T06:43:24.253Z"}
{"level":"info","message":"Swarm listening on /ip4/127.0.0.1/tcp/4001\nSwarm listening on /ip4/192.168.0.31/tcp/4001\nSwarm listening on /ip4/[redacted ip]/tcp/18183\nSwarm listening on /ip6/::1/tcp/4001\n","timestamp":"2016-12-23T06:43:34.264Z"}
{"level":"info","message":"API server listening on /ip4/127.0.0.1/tcp/5001\nGateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080\nDaemon is ready\n","timestamp":"2016-12-23T06:43:34.264Z"}
{"level":"error","message":"\u001b[0;37m00:53:34.262 \u001b[31mERROR \u001b[0;34m      mdns: \u001b[0mmdns lookup error: failed to bind to any unicast udp port \u001b[0;37mmdns.go:131\u001b[0m\n","timestamp":"2016-12-23T06:53:34.263Z"}
{"level":"error","message":"\u001b[0;37m00:56:50.026 \u001b[31mERROR \u001b[0;34m       dht: \u001b[0mno addresses on peer being sent!\n\t\t\t\t\t[local:<peer.ID PKSwzf>]\n\t\t\t\t\t[sending:<peer.ID bJgvyh>]\n\t\t\t\t\t[remote:<peer.ID WcyHKo>] \u001b[0;37mhandlers.go:75\u001b[0m\n","timestamp":"2016-12-23T06:56:50.027Z"}
{"level":"error","message":"\u001b[0;37m01:23:34.262 \u001b[31mERROR \u001b[0;34m      mdns: \u001b[0mmdns lookup error: failed to bind to any unicast udp port \u001b[0;37mmdns.go:131\u001b[0m\n","timestamp":"2016-12-23T07:23:34.263Z"}
{"level":"info","message":"\nReceived interrupt signal, shutting down...\n(Hit ctrl-c again to force-shutdown the daemon.)\n","timestamp":"2016-12-23T07:32:28.169Z"}
{"level":"info","message":"ipfs exited with code: 0, signal: null ","timestamp":"2016-12-23T07:32:28.171Z"}
{"level":"info","message":"Initializing daemon...\n","timestamp":"2016-12-23T15:57:16.918Z"}
{"level":"info","message":"Swarm listening on /ip4/127.0.0.1/tcp/4001\nSwarm listening on /ip4/192.168.0.31/tcp/4001\nSwarm listening on /ip4/[redacted ip]/tcp/17037\nSwarm listening on /ip6/::1/tcp/4001\nAPI server listening on /ip4/127.0.0.1/tcp/5001\n","timestamp":"2016-12-23T15:57:19.286Z"}
{"level":"info","message":"Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080\nDaemon is ready\n","timestamp":"2016-12-23T15:57:19.287Z"}
{"level":"error","message":"\u001b[0;37m11:10:21.152 \u001b[31mERROR \u001b[0;34m       dht: \u001b[0mno addresses on peer being sent!\n\t\t\t\t\t[local:<peer.ID PKSwzf>]\n\t\t\t\t\t[sending:<peer.ID TVsocF>]\n\t\t\t\t\t[remote:<peer.ID WcyHKo>] \u001b[0;37mhandlers.go:75\u001b[0m\n","timestamp":"2016-12-23T17:10:21.154Z"}
{"level":"info","message":"\nReceived interrupt signal, shutting down...\n(Hit ctrl-c again to force-shutdown the daemon.)\n","timestamp":"2016-12-23T18:10:44.475Z"}
{"level":"error","message":"\u001b[0;37m12:10:44.379 \u001b[31mERROR \u001b[0;34mcore/serve: \u001b[0mPath Resolve error: Failed to get block for QmcvZ8YUQsQQeSk9j6M46MWwWY2h5rz15hwLYGRCQtq3uK: context canceled \u001b[0;37mgateway_handler.go:509\u001b[0m\n\u001b[0;37m12:10:44.379 \u001b[31mERROR \u001b[0;34mcore/serve: \u001b[0mPath Resolve error: Failed to get block for QmafJsXHkJ2sZ4f8YoUyQuAphP1HpoggDRX1Aob1gJ6eyk: context canceled \u001b[0;37mgateway_handler.go:509\u001b[0m\n","timestamp":"2016-12-23T18:10:44.476Z"}
{"level":"info","message":"ipfs exited with code: 0, signal: null ","timestamp":"2016-12-23T18:10:44.481Z"}
{"level":"info","message":"Initializing daemon...\n","timestamp":"2016-12-23T18:12:17.197Z"}
{"level":"info","message":"Swarm listening on /ip4/127.0.0.1/tcp/4001\nSwarm listening on /ip4/192.168.0.31/tcp/4001\nSwarm listening on /ip4/[redacted ip]/tcp/32514\nSwarm listening on /ip6/::1/tcp/4001\n","timestamp":"2016-12-23T18:12:19.623Z"}
{"level":"info","message":"API server listening on /ip4/127.0.0.1/tcp/5001\nGateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080\nDaemon is ready\n","timestamp":"2016-12-23T18:12:19.623Z"}
{"level":"info","message":"\nReceived interrupt signal, shutting down...\n(Hit ctrl-c again to force-shutdown the daemon.)\n","timestamp":"2016-12-23T18:12:50.723Z"}
{"level":"info","message":"ipfs exited with code: 0, signal: null ","timestamp":"2016-12-23T18:12:50.725Z"}
{"level":"info","message":"Initializing daemon...\n","timestamp":"2016-12-23T18:18:15.348Z"}
{"level":"info","message":"Swarm listening on /ip4/127.0.0.1/tcp/4001\nSwarm listening on /ip4/192.168.0.31/tcp/4001\nSwarm listening on /ip6/::1/tcp/4001\nAPI server listening on /ip4/127.0.0.1/tcp/5001\n","timestamp":"2016-12-23T18:18:16.673Z"}
{"level":"info","message":"Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080\nDaemon is ready\n","timestamp":"2016-12-23T18:18:16.673Z"}
{"level":"error","message":"\u001b[0;37m12:28:25.362 \u001b[31mERROR \u001b[0;34m      mdns: \u001b[0mmdns lookup error: failed to bind to any unicast udp port \u001b[0;37mmdns.go:131\u001b[0m\n","timestamp":"2016-12-23T18:28:25.366Z"}
{"level":"error","message":"\u001b[0;37m12:29:09.080 \u001b[31mERROR \u001b[0;34m       dht: \u001b[0mno addresses on peer being sent!\n\t\t\t\t\t[local:<peer.ID PKSwzf>]\n\t\t\t\t\t[sending:<peer.ID NRV7ky>]\n\t\t\t\t\t[remote:<peer.ID WcyHKo>] \u001b[0;37mhandlers.go:75\u001b[0m\n","timestamp":"2016-12-23T18:29:09.081Z"}
{"level":"error","message":"\u001b[0;37m12:40:29.770 \u001b[31mERROR \u001b[0;34m       dht: \u001b[0mno addresses on peer being sent!\n\t\t\t\t\t[local:<peer.ID PKSwzf>]\n\t\t\t\t\t[sending:<peer.ID ZziavL>]\n\t\t\t\t\t[remote:<peer.ID WcyHKo>] \u001b[0;37mhandlers.go:75\u001b[0m\n","timestamp":"2016-12-23T18:40:29.771Z"}
{"level":"info","message":"\nReceived interrupt signal, shutting down...\n(Hit ctrl-c again to force-shutdown the daemon.)\n","timestamp":"2016-12-23T18:43:42.674Z"}
{"level":"info","message":"ipfs exited with code: 0, signal: null ","timestamp":"2016-12-23T18:43:42.677Z"}
{"level":"info","message":"Initializing daemon...\n","timestamp":"2016-12-23T19:00:48.101Z"}
{"level":"info","message":"Swarm listening on /ip4/127.0.0.1/tcp/4001\nSwarm listening on /ip4/192.168.0.31/tcp/4001\nSwarm listening on /ip6/::1/tcp/4001\nAPI server listening on /ip4/127.0.0.1/tcp/5001\n","timestamp":"2016-12-23T19:00:49.298Z"}
{"level":"info","message":"Gateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080\nDaemon is ready\n","timestamp":"2016-12-23T19:00:49.299Z"}
{"level":"error","message":"\u001b[0;37m13:02:28.117 \u001b[31mERROR \u001b[0;34m      mdns: \u001b[0mmdns lookup error: failed to bind to any multicast udp port \u001b[0;37mmdns.go:131\u001b[0m\n","timestamp":"2016-12-23T19:02:28.121Z"}
{"level":"error","message":"\u001b[0;37m13:35:39.109 \u001b[31mERROR \u001b[0;34m       dht: \u001b[0mno addresses on peer being sent!\n\t\t\t\t\t[local:<peer.ID PKSwzf>]\n\t\t\t\t\t[sending:<peer.ID a7U9CN>]\n\t\t\t\t\t[remote:<peer.ID WcyHKo>] \u001b[0;37mhandlers.go:75\u001b[0m\n","timestamp":"2016-12-23T19:35:39.111Z"}
{"level":"error","message":"Error: ipfs daemon is running. please stop it to run this command\nUse 'ipfs daemon --help' for information about this command\n","timestamp":"2016-12-23T20:50:44.445Z"}
{"level":"info","message":"ipfs exited with code: 1, signal: null ","timestamp":"2016-12-23T20:50:44.628Z"}
{"level":"error","message":"Error: ipfs daemon is running. please stop it to run this command\nUse 'ipfs daemon --help' for information about this command\n","timestamp":"2016-12-23T20:51:06.675Z"}
{"level":"info","message":"ipfs exited with code: 1, signal: null ","timestamp":"2016-12-23T20:51:06.677Z"}
{"level":"info","message":"Initializing daemon...\n","timestamp":"2016-12-23T20:56:32.208Z"}
{"level":"info","message":"Swarm listening on /ip4/127.0.0.1/tcp/4001\nSwarm listening on /ip4/192.168.0.31/tcp/4001\nSwarm listening on /ip4/[redacted ip]/tcp/50400\nSwarm listening on /ip6/::1/tcp/4001\n","timestamp":"2016-12-23T20:56:34.658Z"}
{"level":"info","message":"API server listening on /ip4/127.0.0.1/tcp/5001\nGateway (readonly) server listening on /ip4/127.0.0.1/tcp/8080\nDaemon is ready\n","timestamp":"2016-12-23T20:56:34.659Z"}
```

`APP.error.log`
```
{"level":"error","message":"Cannot read property 'args' of undefined TypeError: Cannot read property 'args' of undefined\n    at entries.watch (/Applications/AKASHA.app/Contents/Resources/app.asar/main/lib/ipc/modules/notifications/feed.js:61:49)\n    at /Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/filter.js:112:17\n    at Array.forEach (native)\n    at Object.onMessage [as callback] (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/filter.js:111:35)\n    at /Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/requestmanager.js:255:24\n    at Array.filter (native)\n    at Object.<anonymous> (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/requestmanager.js:252:12)\n    at /Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/ipcprovider.js:66:44\n    at Array.forEach (native)\n    at Socket.<anonymous> (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/ipcprovider.js:50:47)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at Pipe.onread (net.js:543:20)","timestamp":"2016-12-23T20:49:04.723Z"}
{"level":"error","message":"You tried to send \"eth_uninstallFilter\" synchronously. Synchronous requests are not supported by the IPC provider. Error: You tried to send \"eth_uninstallFilter\" synchronously. Synchronous requests are not supported by the IPC provider.\n    at IpcProvider.send (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/ipcprovider.js:192:15)\n    at RequestManager.send (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/requestmanager.js:58:32)\n    at Object.send [as uninstallFilter] (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/method.js:145:58)\n    at Filter.stopWatching (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/filter.js:198:36)\n    at RequestManager.reset (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/requestmanager.js:179:29)\n    at Web3.reset (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3.js:82:26)\n    at GethConnector._flushEvents (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/@akashaproject/geth-connector/lib/GethConnector.js:81:19)\n    at GethConnector.stop (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/@akashaproject/geth-connector/lib/GethConnector.js:64:14)\n    at BrowserWindow.mainWindow.once (/Applications/AKASHA.app/Contents/Resources/app.asar/main/index.js:74:58)\n    at BrowserWindow.g (events.js:286:16)\n    at emitOne (events.js:96:13)\n    at BrowserWindow.emit (events.js:188:7)","timestamp":"2016-12-23T20:49:04.876Z"}
```

`APP.info.log`
```
{"level":"error","message":"Cannot read property 'args' of undefined TypeError: Cannot read property 'args' of undefined\n    at entries.watch (/Applications/AKASHA.app/Contents/Resources/app.asar/main/lib/ipc/modules/notifications/feed.js:61:49)\n    at /Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/filter.js:112:17\n    at Array.forEach (native)\n    at Object.onMessage [as callback] (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/filter.js:111:35)\n    at /Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/requestmanager.js:255:24\n    at Array.filter (native)\n    at Object.<anonymous> (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/requestmanager.js:252:12)\n    at /Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/ipcprovider.js:66:44\n    at Array.forEach (native)\n    at Socket.<anonymous> (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/ipcprovider.js:50:47)\n    at emitOne (events.js:96:13)\n    at Socket.emit (events.js:188:7)\n    at readableAddChunk (_stream_readable.js:176:18)\n    at Socket.Readable.push (_stream_readable.js:134:10)\n    at Pipe.onread (net.js:543:20)","timestamp":"2016-12-23T20:49:04.723Z"}
{"level":"error","message":"You tried to send \"eth_uninstallFilter\" synchronously. Synchronous requests are not supported by the IPC provider. Error: You tried to send \"eth_uninstallFilter\" synchronously. Synchronous requests are not supported by the IPC provider.\n    at IpcProvider.send (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/ipcprovider.js:192:15)\n    at RequestManager.send (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/requestmanager.js:58:32)\n    at Object.send [as uninstallFilter] (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/method.js:145:58)\n    at Filter.stopWatching (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/filter.js:198:36)\n    at RequestManager.reset (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3/requestmanager.js:179:29)\n    at Web3.reset (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/web3/lib/web3.js:82:26)\n    at GethConnector._flushEvents (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/@akashaproject/geth-connector/lib/GethConnector.js:81:19)\n    at GethConnector.stop (/Applications/AKASHA.app/Contents/Resources/app.asar/node_modules/@akashaproject/geth-connector/lib/GethConnector.js:64:14)\n    at BrowserWindow.mainWindow.once (/Applications/AKASHA.app/Contents/Resources/app.asar/main/index.js:74:58)\n    at BrowserWindow.g (events.js:286:16)\n    at emitOne (events.js:96:13)\n    at BrowserWindow.emit (events.js:188:7)","timestamp":"2016-12-23T20:49:04.876Z"}
```

**Comment by 42piratas** [comment]
Hey @rabbit 

First, I'm sorry for the late reply. 

Have you tried the latest beta version?

I'm closing this issue because the Alpha version is not supported anymore and the repository will be archived, but if you're still facing the problem with the latest beta version, please let me know in the [/dapp](https://github.com/AkashaProject/dapp) repository and I'll get back to you asap.

And thank you very much for your feedback! We appreciate your contribution. 

Cheers! :pray::metal:
